// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

package cli

import (
	"fmt"
	"sort"
	"strings"
)

// globalFlags are the flags Run accepts before the command. The completion
// scripts offer them; TestCompletionListsEveryCommandAndFlag keeps this list
// equal to the flags Run defines.
var globalFlags = []string{"--store", "--offline"}

// runCompletion prints a completion script for one shell to stdout. The
// command names come from the dispatch table, so a new command is completed
// without editing any script.
func runCompletion(_ string, args []string, env Env) (int, error) {
	if len(args) != 1 {
		return ExitError, fmt.Errorf("completion takes one shell: bash, zsh or fish")
	}
	names := commandNames()
	var script string
	switch args[0] {
	case "bash":
		script = bashCompletion(names)
	case "zsh":
		script = zshCompletion(names)
	case "fish":
		script = fishCompletion(names)
	default:
		return ExitError, fmt.Errorf("completion: shell is %q, want bash, zsh or fish", args[0])
	}
	say(env.Stdout, "%s", script)
	return ExitOK, nil
}

// commandNames is every command Run dispatches, sorted.
func commandNames() []string {
	names := make([]string, 0, len(commands))
	for n := range commands {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func bashCompletion(names []string) string {
	return fmt.Sprintf(`# bash completion for passmcp-graph, generated by passmcp-graph completion bash
_passmcp_graph() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$prev" = "--store" ]; then
    COMPREPLY=($(compgen -d -- "$cur"))
    return
  fi
  COMPREPLY=($(compgen -W "%s %s" -- "$cur"))
}
complete -o default -F _passmcp_graph passmcp-graph
`, strings.Join(names, " "), strings.Join(globalFlags, " "))
}

func zshCompletion(names []string) string {
	return fmt.Sprintf(`#compdef passmcp-graph
# zsh completion for passmcp-graph, generated by passmcp-graph completion zsh
_arguments \
  '--store[directory holding graph.json]:directory:_files -/' \
  '--offline[refuse every network request]' \
  '1:command:(%s)' \
  '*::argument:_files'
`, strings.Join(names, " "))
}

func fishCompletion(names []string) string {
	var b strings.Builder
	b.WriteString("# fish completion for passmcp-graph, generated by passmcp-graph completion fish\n")
	b.WriteString("complete -c passmcp-graph -l store -r -a '(__fish_complete_directories)' -d 'directory holding graph.json'\n")
	b.WriteString("complete -c passmcp-graph -l offline -d 'refuse every network request'\n")
	fmt.Fprintf(&b, "complete -c passmcp-graph -n __fish_use_subcommand -f -a '%s'\n", strings.Join(names, " "))
	return b.String()
}
